server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: #URL del repositorio del proyecto
          searchPath: #Carpeta donde se encuentra los archivos de configuracion